import Header from "@/components/layouts/Header";
import "./globals.css";
// import { GlobalProvider } from "./GlobalProvider";

export const metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({ children }) {
    return (
        <html lang="en">
            <head />
            <body>
                {/* <GlobalProvider> */}
                <Header />
                {children}
                {/* </GlobalProvider> */}
            </body>
        </html>
    );
}
